package com.lq.blog.mapper;

import com.lq.blog.model.Blog;
import com.lq.blog.model.BlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogs
     *
     * @mbg.generated Mon Oct 28 15:32:05 CST 2019
     */
    long countByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogs
     *
     * @mbg.generated Mon Oct 28 15:32:05 CST 2019
     */
    int deleteByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogs
     *
     * @mbg.generated Mon Oct 28 15:32:05 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogs
     *
     * @mbg.generated Mon Oct 28 15:32:05 CST 2019
     */
    int insert(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogs
     *
     * @mbg.generated Mon Oct 28 15:32:05 CST 2019
     */
    int insertSelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogs
     *
     * @mbg.generated Mon Oct 28 15:32:05 CST 2019
     */
    List<Blog> selectByExampleWithRowbounds(BlogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogs
     *
     * @mbg.generated Mon Oct 28 15:32:05 CST 2019
     */
    List<Blog> selectByExample(BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogs
     *
     * @mbg.generated Mon Oct 28 15:32:05 CST 2019
     */
    Blog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogs
     *
     * @mbg.generated Mon Oct 28 15:32:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogs
     *
     * @mbg.generated Mon Oct 28 15:32:05 CST 2019
     */
    int updateByExample(@Param("record") Blog record, @Param("example") BlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogs
     *
     * @mbg.generated Mon Oct 28 15:32:05 CST 2019
     */
    int updateByPrimaryKeySelective(Blog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blogs
     *
     * @mbg.generated Mon Oct 28 15:32:05 CST 2019
     */
    int updateByPrimaryKey(Blog record);
}