package com.lq.blog.mapper;

import com.lq.blog.model.CNotification;
import com.lq.blog.model.CNotificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CNotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnotification
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    long countByExample(CNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnotification
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    int deleteByExample(CNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnotification
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnotification
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    int insert(CNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnotification
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    int insertSelective(CNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnotification
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    List<CNotification> selectByExampleWithRowbounds(CNotificationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnotification
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    List<CNotification> selectByExample(CNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnotification
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    CNotification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnotification
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") CNotification record, @Param("example") CNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnotification
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    int updateByExample(@Param("record") CNotification record, @Param("example") CNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnotification
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    int updateByPrimaryKeySelective(CNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cnotification
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    int updateByPrimaryKey(CNotification record);
}