package com.lq.blog.mapper;

import com.lq.blog.model.MNotification;
import com.lq.blog.model.MNotificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MNotificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnotification
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    long countByExample(MNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnotification
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    int deleteByExample(MNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnotification
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnotification
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    int insert(MNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnotification
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    int insertSelective(MNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnotification
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    List<MNotification> selectByExampleWithRowbounds(MNotificationExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnotification
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    List<MNotification> selectByExample(MNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnotification
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    MNotification selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnotification
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") MNotification record, @Param("example") MNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnotification
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    int updateByExample(@Param("record") MNotification record, @Param("example") MNotificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnotification
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    int updateByPrimaryKeySelective(MNotification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mnotification
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    int updateByPrimaryKey(MNotification record);
}