package com.lq.blog.model;

import java.util.Date;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.id
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.title
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.flags
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private String flags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.firstPicture
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private String firstpicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.view
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private Long view;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.appreciation
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private boolean appreciation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.publish
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private boolean publish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.shareStatement
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private boolean sharestatement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.commentabled
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private boolean commentabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.recommend
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private boolean recommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.typeId
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private Long typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.userId
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.createTime
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.updateTime
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blogs.content
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.id
     *
     * @return the value of blogs.id
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.id
     *
     * @param id the value for blogs.id
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.title
     *
     * @return the value of blogs.title
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.title
     *
     * @param title the value for blogs.title
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.flags
     *
     * @return the value of blogs.flags
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public String getFlags() {
        return flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.flags
     *
     * @param flags the value for blogs.flags
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setFlags(String flags) {
        this.flags = flags == null ? null : flags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.firstPicture
     *
     * @return the value of blogs.firstPicture
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public String getFirstpicture() {
        return firstpicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.firstPicture
     *
     * @param firstpicture the value for blogs.firstPicture
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setFirstpicture(String firstpicture) {
        this.firstpicture = firstpicture == null ? null : firstpicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.view
     *
     * @return the value of blogs.view
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public Long getView() {
        return view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.view
     *
     * @param view the value for blogs.view
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setView(Long view) {
        this.view = view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.appreciation
     *
     * @return the value of blogs.appreciation
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public boolean getAppreciation() {
        return appreciation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.appreciation
     *
     * @param appreciation the value for blogs.appreciation
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setAppreciation(boolean appreciation) {
        this.appreciation = appreciation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.publish
     *
     * @return the value of blogs.publish
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public boolean getPublish() {
        return publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.publish
     *
     * @param publish the value for blogs.publish
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setPublish(boolean publish) {
        this.publish = publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.shareStatement
     *
     * @return the value of blogs.shareStatement
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public boolean getSharestatement() {
        return sharestatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.shareStatement
     *
     * @param sharestatement the value for blogs.shareStatement
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setSharestatement(boolean sharestatement) {
        this.sharestatement = sharestatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.commentabled
     *
     * @return the value of blogs.commentabled
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public boolean getCommentabled() {
        return commentabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.commentabled
     *
     * @param commentabled the value for blogs.commentabled
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setCommentabled(boolean commentabled) {
        this.commentabled = commentabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.recommend
     *
     * @return the value of blogs.recommend
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public boolean getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.recommend
     *
     * @param recommend the value for blogs.recommend
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setRecommend(boolean recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.typeId
     *
     * @return the value of blogs.typeId
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public Long getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.typeId
     *
     * @param typeid the value for blogs.typeId
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setTypeid(Long typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.userId
     *
     * @return the value of blogs.userId
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.userId
     *
     * @param userid the value for blogs.userId
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.createTime
     *
     * @return the value of blogs.createTime
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.createTime
     *
     * @param createtime the value for blogs.createTime
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.updateTime
     *
     * @return the value of blogs.updateTime
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.updateTime
     *
     * @param updatetime the value for blogs.updateTime
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blogs.content
     *
     * @return the value of blogs.content
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blogs.content
     *
     * @param content the value for blogs.content
     *
     * @mbg.generated Sun Oct 27 10:52:17 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}