package com.lq.blog.model;

import java.util.Date;

public class CNotification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnotification.id
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnotification.notifier
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    private String notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnotification.recevier
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    private String recevier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnotification.blog_id
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnotification.blog_title
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    private String blogTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnotification.type
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnotification.status
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cnotification.createTime
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnotification.id
     *
     * @return the value of cnotification.id
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnotification.id
     *
     * @param id the value for cnotification.id
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnotification.notifier
     *
     * @return the value of cnotification.notifier
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public String getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnotification.notifier
     *
     * @param notifier the value for cnotification.notifier
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public void setNotifier(String notifier) {
        this.notifier = notifier == null ? null : notifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnotification.recevier
     *
     * @return the value of cnotification.recevier
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public String getRecevier() {
        return recevier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnotification.recevier
     *
     * @param recevier the value for cnotification.recevier
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public void setRecevier(String recevier) {
        this.recevier = recevier == null ? null : recevier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnotification.blog_id
     *
     * @return the value of cnotification.blog_id
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnotification.blog_id
     *
     * @param blogId the value for cnotification.blog_id
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnotification.blog_title
     *
     * @return the value of cnotification.blog_title
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnotification.blog_title
     *
     * @param blogTitle the value for cnotification.blog_title
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnotification.type
     *
     * @return the value of cnotification.type
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnotification.type
     *
     * @param type the value for cnotification.type
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnotification.status
     *
     * @return the value of cnotification.status
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnotification.status
     *
     * @param status the value for cnotification.status
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cnotification.createTime
     *
     * @return the value of cnotification.createTime
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cnotification.createTime
     *
     * @param createtime the value for cnotification.createTime
     *
     * @mbg.generated Fri Nov 15 10:09:35 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}