package com.lq.blog.model;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.admin_comment
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    private Boolean adminComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.avatar
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_time
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.email
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.nickname
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.blog_id
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parent_comment_id
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    private Long parentCommentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.state
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.admin_comment
     *
     * @return the value of comment.admin_comment
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public Boolean getAdminComment() {
        return adminComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.admin_comment
     *
     * @param adminComment the value for comment.admin_comment
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public void setAdminComment(Boolean adminComment) {
        this.adminComment = adminComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.avatar
     *
     * @return the value of comment.avatar
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.avatar
     *
     * @param avatar the value for comment.avatar
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_time
     *
     * @return the value of comment.create_time
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_time
     *
     * @param createTime the value for comment.create_time
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.email
     *
     * @return the value of comment.email
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.email
     *
     * @param email the value for comment.email
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.nickname
     *
     * @return the value of comment.nickname
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.nickname
     *
     * @param nickname the value for comment.nickname
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.blog_id
     *
     * @return the value of comment.blog_id
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.blog_id
     *
     * @param blogId the value for comment.blog_id
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parent_comment_id
     *
     * @return the value of comment.parent_comment_id
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public Long getParentCommentId() {
        return parentCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parent_comment_id
     *
     * @param parentCommentId the value for comment.parent_comment_id
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public void setParentCommentId(Long parentCommentId) {
        this.parentCommentId = parentCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.state
     *
     * @return the value of comment.state
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.state
     *
     * @param state the value for comment.state
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbg.generated Thu Oct 31 10:25:47 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}