package com.lq.blog.model;

import java.util.ArrayList;
import java.util.List;

public class DetailsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public DetailsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andBlogIdIsNull() {
            addCriterion("blog_id is null");
            return (Criteria) this;
        }

        public Criteria andBlogIdIsNotNull() {
            addCriterion("blog_id is not null");
            return (Criteria) this;
        }

        public Criteria andBlogIdEqualTo(Long value) {
            addCriterion("blog_id =", value, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdNotEqualTo(Long value) {
            addCriterion("blog_id <>", value, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdGreaterThan(Long value) {
            addCriterion("blog_id >", value, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdGreaterThanOrEqualTo(Long value) {
            addCriterion("blog_id >=", value, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdLessThan(Long value) {
            addCriterion("blog_id <", value, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdLessThanOrEqualTo(Long value) {
            addCriterion("blog_id <=", value, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdIn(List<Long> values) {
            addCriterion("blog_id in", values, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdNotIn(List<Long> values) {
            addCriterion("blog_id not in", values, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdBetween(Long value1, Long value2) {
            addCriterion("blog_id between", value1, value2, "blogId");
            return (Criteria) this;
        }

        public Criteria andBlogIdNotBetween(Long value1, Long value2) {
            addCriterion("blog_id not between", value1, value2, "blogId");
            return (Criteria) this;
        }

        public Criteria andSaveAccountIsNull() {
            addCriterion("save_account is null");
            return (Criteria) this;
        }

        public Criteria andSaveAccountIsNotNull() {
            addCriterion("save_account is not null");
            return (Criteria) this;
        }

        public Criteria andSaveAccountEqualTo(Integer value) {
            addCriterion("save_account =", value, "saveAccount");
            return (Criteria) this;
        }

        public Criteria andSaveAccountNotEqualTo(Integer value) {
            addCriterion("save_account <>", value, "saveAccount");
            return (Criteria) this;
        }

        public Criteria andSaveAccountGreaterThan(Integer value) {
            addCriterion("save_account >", value, "saveAccount");
            return (Criteria) this;
        }

        public Criteria andSaveAccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("save_account >=", value, "saveAccount");
            return (Criteria) this;
        }

        public Criteria andSaveAccountLessThan(Integer value) {
            addCriterion("save_account <", value, "saveAccount");
            return (Criteria) this;
        }

        public Criteria andSaveAccountLessThanOrEqualTo(Integer value) {
            addCriterion("save_account <=", value, "saveAccount");
            return (Criteria) this;
        }

        public Criteria andSaveAccountIn(List<Integer> values) {
            addCriterion("save_account in", values, "saveAccount");
            return (Criteria) this;
        }

        public Criteria andSaveAccountNotIn(List<Integer> values) {
            addCriterion("save_account not in", values, "saveAccount");
            return (Criteria) this;
        }

        public Criteria andSaveAccountBetween(Integer value1, Integer value2) {
            addCriterion("save_account between", value1, value2, "saveAccount");
            return (Criteria) this;
        }

        public Criteria andSaveAccountNotBetween(Integer value1, Integer value2) {
            addCriterion("save_account not between", value1, value2, "saveAccount");
            return (Criteria) this;
        }

        public Criteria andLikeAccountIsNull() {
            addCriterion("like_account is null");
            return (Criteria) this;
        }

        public Criteria andLikeAccountIsNotNull() {
            addCriterion("like_account is not null");
            return (Criteria) this;
        }

        public Criteria andLikeAccountEqualTo(Integer value) {
            addCriterion("like_account =", value, "likeAccount");
            return (Criteria) this;
        }

        public Criteria andLikeAccountNotEqualTo(Integer value) {
            addCriterion("like_account <>", value, "likeAccount");
            return (Criteria) this;
        }

        public Criteria andLikeAccountGreaterThan(Integer value) {
            addCriterion("like_account >", value, "likeAccount");
            return (Criteria) this;
        }

        public Criteria andLikeAccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("like_account >=", value, "likeAccount");
            return (Criteria) this;
        }

        public Criteria andLikeAccountLessThan(Integer value) {
            addCriterion("like_account <", value, "likeAccount");
            return (Criteria) this;
        }

        public Criteria andLikeAccountLessThanOrEqualTo(Integer value) {
            addCriterion("like_account <=", value, "likeAccount");
            return (Criteria) this;
        }

        public Criteria andLikeAccountIn(List<Integer> values) {
            addCriterion("like_account in", values, "likeAccount");
            return (Criteria) this;
        }

        public Criteria andLikeAccountNotIn(List<Integer> values) {
            addCriterion("like_account not in", values, "likeAccount");
            return (Criteria) this;
        }

        public Criteria andLikeAccountBetween(Integer value1, Integer value2) {
            addCriterion("like_account between", value1, value2, "likeAccount");
            return (Criteria) this;
        }

        public Criteria andLikeAccountNotBetween(Integer value1, Integer value2) {
            addCriterion("like_account not between", value1, value2, "likeAccount");
            return (Criteria) this;
        }

        public Criteria andDisalikeCountIsNull() {
            addCriterion("disalike_count is null");
            return (Criteria) this;
        }

        public Criteria andDisalikeCountIsNotNull() {
            addCriterion("disalike_count is not null");
            return (Criteria) this;
        }

        public Criteria andDisalikeCountEqualTo(Integer value) {
            addCriterion("disalike_count =", value, "disalikeCount");
            return (Criteria) this;
        }

        public Criteria andDisalikeCountNotEqualTo(Integer value) {
            addCriterion("disalike_count <>", value, "disalikeCount");
            return (Criteria) this;
        }

        public Criteria andDisalikeCountGreaterThan(Integer value) {
            addCriterion("disalike_count >", value, "disalikeCount");
            return (Criteria) this;
        }

        public Criteria andDisalikeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("disalike_count >=", value, "disalikeCount");
            return (Criteria) this;
        }

        public Criteria andDisalikeCountLessThan(Integer value) {
            addCriterion("disalike_count <", value, "disalikeCount");
            return (Criteria) this;
        }

        public Criteria andDisalikeCountLessThanOrEqualTo(Integer value) {
            addCriterion("disalike_count <=", value, "disalikeCount");
            return (Criteria) this;
        }

        public Criteria andDisalikeCountIn(List<Integer> values) {
            addCriterion("disalike_count in", values, "disalikeCount");
            return (Criteria) this;
        }

        public Criteria andDisalikeCountNotIn(List<Integer> values) {
            addCriterion("disalike_count not in", values, "disalikeCount");
            return (Criteria) this;
        }

        public Criteria andDisalikeCountBetween(Integer value1, Integer value2) {
            addCriterion("disalike_count between", value1, value2, "disalikeCount");
            return (Criteria) this;
        }

        public Criteria andDisalikeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("disalike_count not between", value1, value2, "disalikeCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table details
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 25 10:04:40 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table details
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}