package com.lq.blog.model;

public class Details {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.user_id
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.blog_id
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    private Long blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.save_account
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    private Integer saveAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.like_account
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    private Integer likeAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column details.disalike_count
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    private Integer disalikeCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.user_id
     *
     * @return the value of details.user_id
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.user_id
     *
     * @param userId the value for details.user_id
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.blog_id
     *
     * @return the value of details.blog_id
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.blog_id
     *
     * @param blogId the value for details.blog_id
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.save_account
     *
     * @return the value of details.save_account
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public Integer getSaveAccount() {
        return saveAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.save_account
     *
     * @param saveAccount the value for details.save_account
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public void setSaveAccount(Integer saveAccount) {
        this.saveAccount = saveAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.like_account
     *
     * @return the value of details.like_account
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public Integer getLikeAccount() {
        return likeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.like_account
     *
     * @param likeAccount the value for details.like_account
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public void setLikeAccount(Integer likeAccount) {
        this.likeAccount = likeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column details.disalike_count
     *
     * @return the value of details.disalike_count
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public Integer getDisalikeCount() {
        return disalikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column details.disalike_count
     *
     * @param disalikeCount the value for details.disalike_count
     *
     * @mbg.generated Mon Nov 25 10:04:40 CST 2019
     */
    public void setDisalikeCount(Integer disalikeCount) {
        this.disalikeCount = disalikeCount;
    }
}