package com.lq.blog.model;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.admin_reply
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    private Boolean adminReply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.avatar
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.email
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.nickname
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.parent_message_id
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    private Long parentMessageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.state
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.user_Id
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.admin_reply
     *
     * @return the value of message.admin_reply
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public Boolean getAdminReply() {
        return adminReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.admin_reply
     *
     * @param adminReply the value for message.admin_reply
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public void setAdminReply(Boolean adminReply) {
        this.adminReply = adminReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.avatar
     *
     * @return the value of message.avatar
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.avatar
     *
     * @param avatar the value for message.avatar
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.email
     *
     * @return the value of message.email
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.email
     *
     * @param email the value for message.email
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.nickname
     *
     * @return the value of message.nickname
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.nickname
     *
     * @param nickname the value for message.nickname
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.parent_message_id
     *
     * @return the value of message.parent_message_id
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public Long getParentMessageId() {
        return parentMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.parent_message_id
     *
     * @param parentMessageId the value for message.parent_message_id
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public void setParentMessageId(Long parentMessageId) {
        this.parentMessageId = parentMessageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.state
     *
     * @return the value of message.state
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.state
     *
     * @param state the value for message.state
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.user_Id
     *
     * @return the value of message.user_Id
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.user_Id
     *
     * @param userId the value for message.user_Id
     *
     * @mbg.generated Mon Nov 11 09:23:41 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}