package com.lq.blog.model;

import java.util.Date;

public class MNotification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnotification.id
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnotification.nickname
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnotification.type
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnotification.createTime
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mnotification.state
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnotification.id
     *
     * @return the value of mnotification.id
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnotification.id
     *
     * @param id the value for mnotification.id
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnotification.nickname
     *
     * @return the value of mnotification.nickname
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnotification.nickname
     *
     * @param nickname the value for mnotification.nickname
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnotification.type
     *
     * @return the value of mnotification.type
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnotification.type
     *
     * @param type the value for mnotification.type
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnotification.createTime
     *
     * @return the value of mnotification.createTime
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnotification.createTime
     *
     * @param createtime the value for mnotification.createTime
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mnotification.state
     *
     * @return the value of mnotification.state
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mnotification.state
     *
     * @param state the value for mnotification.state
     *
     * @mbg.generated Fri Nov 15 15:51:24 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }
}