package com.lq.blog.model;

public class Problem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.id
     *
     * @mbg.generated Fri Nov 22 08:57:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problem
     *
     * @mbg.generated Fri Nov 22 08:57:51 CST 2019
     */
    private String problem;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.id
     *
     * @return the value of problem.id
     *
     * @mbg.generated Fri Nov 22 08:57:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.id
     *
     * @param id the value for problem.id
     *
     * @mbg.generated Fri Nov 22 08:57:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problem
     *
     * @return the value of problem.problem
     *
     * @mbg.generated Fri Nov 22 08:57:51 CST 2019
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problem
     *
     * @param problem the value for problem.problem
     *
     * @mbg.generated Fri Nov 22 08:57:51 CST 2019
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }
}